# Generated by Django 5.0 on 2024-03-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QAs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserQuestion',
        ),
    ]
