# Generated by Django 5.0 on 2024-03-24 21:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAs', '0002_delete_userquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(default='none', max_length=150)),
                ('score', models.BooleanField(default=False)),
                ('times_attempted', models.IntegerField(default=0)),
                ('date_attempted', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QAs.question')),
            ],
            options={
                'unique_together': {('user_username', 'question')},
            },
        ),
    ]
