# Generated by Django 4.2.6 on 2023-10-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAs', '0003_alter_exercise_difficulty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Eedium'), ('Hard', 'Hard')], max_length=50),
        ),
    ]
