# Generated by Django 5.0 on 2024-03-27 16:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAs', '0003_userquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=10)),
                ('questions_to_attempt', models.IntegerField(default=0)),
                ('questions_attempted', models.IntegerField(default=0)),
                ('username', models.CharField(default='none', max_length=150)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
