# Generated by Django 5.0 on 2024-03-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAs', '0004_lessonplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='completed',
            field=models.IntegerField(default=0),
        ),
    ]
