# Generated by Django 5.0 on 2024-03-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAs', '0005_lessonplan_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Previous_LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('topic', models.CharField(max_length=100)),
                ('questions_present', models.TextField()),
                ('username', models.CharField(default='none', max_length=150)),
            ],
        ),
    ]
