# Generated by Django 5.0.3 on 2024-03-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QAs", "0007_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="experience_level",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="experience",
            name="preferred_frequency",
            field=models.IntegerField(),
        ),
    ]
