# Generated by Django 5.0.3 on 2024-03-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("QAs", "0008_alter_experience_experience_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="username",
            field=models.CharField(default="none", max_length=150),
        ),
    ]
