# Generated by Django 5.0 on 2024-03-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAs', '0009_experience_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='experience_level',
            field=models.IntegerField(default='Easy'),
        ),
    ]
