# Generated by Django 4.2.6 on 2023-10-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAs', '0002_remove_exercise_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'easy'), ('Medium', 'medium'), ('Hard', 'hard')], max_length=50),
        ),
    ]
